export const FETCH_MOST_VIEWED_ARTICLES_REQUEST = 'FETCH_MOST_VIEWED_ARTICLES_REQUEST';
export const FETCH_MOST_VIEWED_ARTICLES_SUCCESS = 'FETCH_MOST_VIEWED_ARTICLES_SUCCESS';
export const FETCH_MOST_VIEWED_ARTICLES_FAILURE = 'FETCH_MOST_VIEWED_ARTICLES_FAILED';
